version = 1

[schema]

[[schema.tables]]
id = 0
name = "documents"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "project_id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "slug"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "title"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "current_revision_id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "archived_at"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "updated_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_documents_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_documents_by_project_id_and_slug"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 0, index = 2 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 0, index = 2 }
name = "index_documents_by_archived_at"
on = 0
columns = [{ column = { table = 0, index = 5 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 0, index = 3 }
name = "index_documents_by_updated_at"
on = 0
columns = [{ column = { table = 0, index = 7 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 1
name = "blobs"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "hash"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "size"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_blobs_by_hash"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "revisions"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "document_id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "number"
ty = "U32"
storage_ty = { UnsignedInteger = 4 }

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "blob_hash"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "message"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "author_name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 6 }
name = "source"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 7 }
name = "restored_from_number"
ty = "U32"
storage_ty = { UnsignedInteger = 4 }
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 8 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_revisions_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_revisions_by_document_id_and_number"
on = 2
columns = [{ column = { table = 2, index = 1 }, op = "Eq", scope = "Partition" }, { column = { table = 2, index = 2 }, op = "Eq", scope = "Local" }]
unique = true

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_revisions_by_author_name"
on = 2
columns = [{ column = { table = 2, index = 5 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "projects"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "slug"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "description"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "color"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "archived_at"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 6 }
name = "created_at"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_projects_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_projects_by_slug"
on = 3
columns = [{ column = { table = 3, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables.indices]]
id = { table = 3, index = 2 }
name = "index_projects_by_archived_at"
on = 3
columns = [{ column = { table = 3, index = 5 }, op = "Eq", scope = "Partition" }]
